/*

Package controllers_test tests the autogenerated
scaffold outputs. Gock is used to mock the
go-github api calls.

*/
package controllers_test

import (
	"testing"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

func TestControllers(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Controllers Suite")
}
