/*

Package controllers is an autogenerated
package containing scaffold outputs
as well as manually created sub-packages
and files.

*/
package controllers

import (
	"github.com/goadesign/goa"
)

// SwaggerController implements the swagger resource.
type SwaggerController struct {
	*goa.Controller
}

// NewSwaggerController creates a swagger controller.
func NewSwaggerController(service *goa.Service) *SwaggerController {
	return &SwaggerController{Controller: service.NewController("SwaggerController")}
}
